In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
import matplotlib.pyplot as plt

In [11]:
dataset = pd.read_csv("lifeexpectancy_usa.csv")

In [12]:
print(dataset.shape)

(57, 8)


In [13]:
dataset.head()

LOCATION INDICATOR SUBJECT MEASURE FREQUENCY  TIME  Value  Flag Codes
0      USA   LIFEEXP     MEN      YR         A  1960   66.6         NaN
1      USA   LIFEEXP     MEN      YR         A  1961   67.1         NaN
2      USA   LIFEEXP     MEN      YR         A  1962   66.9         NaN
3      USA   LIFEEXP     MEN      YR         A  1963   66.6         NaN
4      USA   LIFEEXP     MEN      YR         A  1964   66.8         NaN

In [14]:
dataset.tail()

LOCATION INDICATOR SUBJECT MEASURE FREQUENCY  TIME  Value  Flag Codes
52      USA   LIFEEXP     MEN      YR         A  2012   76.4         NaN
53      USA   LIFEEXP     MEN      YR         A  2013   76.4         NaN
54      USA   LIFEEXP     MEN      YR         A  2014   76.5         NaN
55      USA   LIFEEXP     MEN      YR         A  2015   76.3         NaN
56      USA   LIFEEXP     MEN      YR         A  2016   76.1         NaN

In [15]:
dataset.describe()

TIME      Value  Flag Codes
count    57.000000  57.000000         0.0
mean   1988.000000  71.475439         NaN
std      16.598193   3.369097         NaN
min    1960.000000  66.600000         NaN
25%    1974.000000  68.200000         NaN
50%    1988.000000  71.400000         NaN
75%    2002.000000  74.400000         NaN
max    2016.000000  76.500000         NaN

In [16]:
X = dataset['TIME'].values

In [17]:
X

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016], dtype=int64)

In [18]:
Y = dataset['Value'].values

In [16]:
Y

array([66.6, 67.1, 66.9, 66.6, 66.8, 66.8, 66.7, 67. , 66.6, 66.8, 67.1,
       67.4, 67.4, 67.6, 68.2, 68.8, 69.1, 69.5, 69.6, 70. , 70. , 70.4,
       70.8, 71. , 71.1, 71.1, 71.2, 71.4, 71.4, 71.7, 71.8, 72. , 72.3,
       72.2, 72.4, 72.5, 73.1, 73.6, 73.8, 73.9, 74.1, 74.3, 74.4, 74.5,
       75. , 75. , 75.2, 75.5, 75.6, 76. , 76.2, 76.3, 76.4, 76.4, 76.5,
       76.3, 76.1])

In [19]:
mean_x=np.mean(X)

In [18]:
mean_x

1988.0

In [21]:
mean_y=np.mean(Y)

In [22]:
mean_y

71.47543859649123

In [23]:
m = len(X)

numer=0
denom=0

for i in range (m):
    numer += (X[i]- mean_x) * (Y[i] - mean_y)
    denom += (X[i]- mean_x) ** 2
    b1= numer/denom
    b0= mean_y - (b1 * mean_x)

print(b1,b0)    

0.20135467980295568 -328.8176648517846


In [24]:
max_x= np.max(X) + 10


In [25]:
min_x = np.min(X) - 10

In [26]:
max_x

2026

In [27]:
min_x

1950

In [28]:
x = np.linspace(min_x, max_x, 10)

In [29]:
y = b0 + b1 * x

In [30]:
x

array([1950.        , 1958.44444444, 1966.88888889, 1975.33333333,
       1983.77777778, 1992.22222222, 2000.66666667, 2009.11111111,
       2017.55555556, 2026.        ])

In [31]:
y

array([63.82396076, 65.52428917, 67.22461758, 68.92494599, 70.62527439,
       72.3256028 , 74.02593121, 75.72625961, 77.42658802, 79.12691643])